baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Terramate Internship'
theme = ["reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "reveal-hugo/themes/sunblind.css"
